import 'package:flutter/services.dart';

class FontService {
  static const String kQuoteEthiopicFont = 'NotoSerifEthiopic';

  /// Checks if the required font is loadable.
  /// Since we cannot easily check installed system fonts across all platforms in pure Dart without native code,
  /// we primarily check if our asset font is loaded or if we can successfully render text (indirectly).
  ///
  /// However, for this MVP, we will assume if we included it in assets (which we should have), it's there.
  /// If the user meant "System Installed Font", that's harder.
  /// We will implement a check that verifies if the asset bundle contains the font manifest.
  static Future<bool> isFontAvailable() async {
    try {
      // This mainly checks if the font is declared in the FontManifest.json (generated by Flutter)
      await rootBundle.load('assets/fonts/toto_serif_ethiopic.ttf');
      return true;
    } catch (e) {
      // If asset load fails, we might still be okay if it's a system font,
      // but the requirement was about "Tofu protection", implying we want to ensure we HAVE it.
      return false;
    }
  }
}
